### PR TITLE
config: allow protocol selection

### PR DESCRIPTION
**Pull request by miekg**
This introduces protocol into the config with 3 allowed values: "arp",
"bgp" and "rip", this specifices what protocol the "speaker" binary
speaks.

### CODE REVIEW

**Comment by miekg** [comment]
@danderson this is a first step to merging the speakers into one binary - if you like it that is.

**Comment by miekg** [comment]
#76 has all the fixed that this PR doesn't have

**Comment by danderson** [comment]
I think this branch got merged in the other PR, I see all the same code.

**Comment by miekg** [comment]
Yes. In branched this of the another branch. End result should be ok
though, I hope?

**Comment by danderson** [comment]
Yes, but this got merged already. When I merged the other PR, it pulled in this code as well. If you look at the code in master, it already has these changes (that's also why the PR now complains about merge conflicts).

So I think we can just close this PR, this code is already merged.

**Comment by danderson** [comment]
To be clear: the result lgtm, I was just making sure I can close this PR without merging, because the code is already merged.

**Pull request closed without merging**
