### PR TITLE
Withdraw announcement w/o healthy endpoints for TrafficPolicy Cluster

### LINKED ISSUE #312: BGP route not withdrawn for svc with externalTrafficPolicy=Cluster and empty endpoint list
**Is this a bug report or a feature request?**:
bug report

**What happened**:
A service of type loadBalancer, announced via BGP, lost all its pod because their health checks failed. The endpoint list was empty because of that, but metallb kept announcing the IP address. 
For externalTrafficPolicy=Local, the announcement was withdrawn. 

**What you expected to happen**:
With no healthy endpoints, the announcement should be withdrawn. For us, this is required in the context of a failover to another datacenter where the service is still healthy. 

**How to reproduce it (as minimally and precisely as possible)**:
Single-Pod deployment (e.g. nginx) with a service of type LoadBalancer and externalTrafficPolicy=Cluster
When scaling the deployment down to 0, the announcement stays up, but shouldn't. 

**Anything else we need to know?**:
As mentioned the withdrawal of the announcement when the cluster does not contain a healthy endpoint anymore is essential for a redundancy failover to another datacenter. 

**Environment**:
- MetalLB version: 0.6.2 and 0.7.3
- Kubernetes version: 1.11.2
- BGP router type/version: Cisco 9k
- OS (e.g. from /etc/os-release): ContainerLinux 1855.4.0
- Kernel (e.g. `uname -a`): 4.14.67-coreos

### PR DESCRIPTION
**Pull request by sfudeus**
**What this PR does / why we need it**:

This PR ensures that BGP announcements are withdrawn for extrernalTrafficPolicy Cluster when no healthy endpoint is available. This is essential for geo redundancy setups with multiple datacenters, where traffic should be automatically shifted via BGP to the fail over datacenter when a service gets unhealthy. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #312 

**Special notes for your reviewer**:
The largest addition is `healthyEndpointExists`, which mostly is a copy of `nodeHasHealthyEndpoint`, but without the filtering on a specific node. The logic is the same. 
The real change is the `else if` branch in `ShouldAnounce`.

### CODE REVIEW

**Comment by sfudeus** [comment]
Corporate CLA might take a bit, I'm on it :-/

**Comment by danderson** [comment]
Any news on a CLA? Unfortunately I can't take patches without one, that's part of the deal where Google allowed me to open-source this :(

**Comment by sfudeus** [comment]
Hi @danderson, no progress unfortunately, but I'm still on it. 
Is the PR otherwise acceptable for you? Anything to adapt?

**Comment by danderson** [comment]
The change looks fine (and addresses something I didn't think of at all, since I don't run anycast services), I think it's ready to merge as soon as the cla/google robot is happy.

**Comment by sfudeus** [comment]
It took a while, but the CLA is signed now, finally ...

**Comment by sfudeus** [comment]
rebased to current master

**Pull request merged**
