### PR TITLE
Update minikube.md

### PR DESCRIPTION
**Pull request by driftavalli**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by driftavalli** [comment]
I signed it!

**Comment by danderson** [comment]
Thanks for the pull request! It looks like CLA Bot is still unhappy. Did you sign the CLA using the same email you use for git? CLA Bot is looking at the commit and trying to find your CLA using that email.

**Comment by danderson** [comment]
CLA bot is still unhappy. Can you check that you used the same emails and stuff to sign the CLA?

Unfortunately unless the CLA bot gives me a green light, I can't merge this, as much as I want to :(

**Comment by driftavalli** [comment]
I did use the same email but my email is set to private on github, does
that make a difference?

**Comment by danderson** [comment]
Huh, weird, CLA bot is happy now. Sorry for the confusion, and thank you for taking the time to fix the documentation!

**Comment by danderson** [comment]
What name would you like me to use to credit your contribution? I only have your github username, but usually I use full names in release credits (example: https://metallb.universe.tf/release-notes/#version-0-3-0). Let me know how you'd like to be credited, and I'll update the 0.4 release notes!

**Comment by driftavalli** [comment]
My full name is Oga Ajima. Not sure my contribution really merits a credit
but if it's okay, it will be nice.

**Comment by danderson** [comment]
IMO, every contribution deserves credit. You could have just ignored the mistake, but instead you sent a PR to make things better! I'm very grateful for that, and it deserves an "official" thank-you :)

Credits updated in https://github.com/google/metallb/commit/e14c13a69377c91e4a0e74c6cf2963e163e3deb4 . I'll probably release v0.4.0 in a few hours, and the website will update then.

**Pull request merged**
